// <auto-generated />
namespace CreateDB.ADOD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_column_deployment_lastModifiedOn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_column_deployment_lastModifiedOn));
        
        string IMigrationMetadata.Id
        {
            get { return "201811281120508_add_column_deployment_lastModifiedOn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
