// <auto-generated />
namespace CreateDB.ADOD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_column_releaseEjecutionEnvironment_environmentId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_column_releaseEjecutionEnvironment_environmentId));
        
        string IMigrationMetadata.Id
        {
            get { return "201811271507290_change_column_releaseEjecutionEnvironment_environmentId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
